# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

pool:
  vmImage: ubuntu-18.04

stages:

- stage: Destroy
  displayName: Terraform Destroy
  jobs:
    - job:
      
      steps:
        
        - task: TerraformInstaller@0
          displayName: Install terraform
          inputs:
           terraformVersion: '1.0.0'
        
        
        - task: TerraformTaskV2@2
          displayName: Terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/k8s'
            backendServiceArm: 'Pay-As-You-Go (9f5e6f55-0b11-4062-9a61-94be3d06c950)'
            backendAzureRmResourceGroupName: 'shell21'
            backendAzureRmStorageAccountName: 'shell21'
            backendAzureRmContainerName: 'terraform'
            backendAzureRmKey: 'terraform.tfstate'

        - task: TerraformTaskV2@2
          displayName: Terraform Destroy
          inputs:
            provider: 'azurerm'
            command: 'destroy'
            workingDirectory: '$(System.DefaultWorkingDirectory)/k8s'
            environmentServiceNameAzureRM: 'Pay-As-You-Go (9f5e6f55-0b11-4062-9a61-94be3d06c950)'